apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
    namespace: ex2
  name: web
spec:
  containers:
  - name: web
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "1.0"
        memory: "1G"
      limits:
        cpu: "1.0"
        memory: "1G"
